<a href="https://colab.research.google.com/github/juanroarodriguez-source/curso-ia-para-economia/blob/main/clases/3_Analisis_y_visualizacion_datos/1_Importacion_Extraccion_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/LinaMariaCastro/curso-ia-para-economia/blob/main/clases/3_Analisis_y_visualizacion_datos/1_Importacion_Extraccion_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Inteligencia Artificial con Aplicaciones en Economía I**

- 👩‍🏫 **Profesora:** [Lina María Castro](https://www.linkedin.com/in/lina-maria-castro)  
- 📧 **Email:** [lmcastroco@gmail.com](mailto:lmcastroco@gmail.com)  
- 🎓 **Universidad:** Universidad Externado de Colombia - Facultad de Economía

# 🛢️**Métodos de importación y extracción de datos**

En esta clase aprenderás a:

- Importar y extraer datos desde diferentes fuentes:

  - Archivos locales (CSV, Excel, TXT)
  - Archivos en la web (CSV desde URL)
  - APIs

- Explorar el dataset

Este es el primer paso para todo análisis de datos en economía y ciencias sociales.

## Instalaciones necesarias

No es necesario si:
- Instalaste los programas del archivo requirements.txt
- Corriste el notebook "0_instalacion_librerias.ipynb"
- Estás usando Google Colab

In [1]:
# Para poder leer y abrir archivos de Excel
!pip install xlrd openpyxl

Requirement already satisfied: xlrd in /usr/local/lib/python3.13/dist-packages (2.0.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.13/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.13/dist-packages (from openpyxl) (2.0.0)

In [2]:
# Para trabajar datos tabulares
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

## Importar librerías

In [33]:
import numpy as np
import pandas as pd

## Mejorar visualización de los dataframes

In [ ]:
# Que muestre todas las columnas
pd.options.display.max_columns = None
# En los dataframes, mostrar los float con dos decimales
pd.options.display.float_format = '{:,.2f}'.format

## Importar datos desde archivos CSV, Excel, TXT

En Google Colab hay dos opciones:
- Subir el archivo al entorno (se borra cuando se desconecta del entorno de ejecución o se cierra el notebook)
- Importar el archivo desde Google Drive

### Subir el archivo al entorno

In [5]:
# Archivo csv
df_ssc = pd.read_csv('Supersociedades_2023.csv', encoding='utf-8', dtype=str) #latin-1
df_ssc.head()

,RANKING,NIT,RAZON_SOCIAL,CODIGO_DEPARTAMENTO,DEPARTAMENTO,CODIGO_MUNICIPIO,MUNICIPIO,CIIU,DESCRIPCION_CIIU,AÑOS_EMPRESA,...,ACTIVOS_2022,PASIVOS_2022,PATRIMONIO_2022,INGRESOS_OPERACIONALES_2022,UTILIDAD_2022,DIRECCION,TELEFONO,CELULAR,EMAIL,SUPERVISOR
0,1,899999068,ECOPETROL S.A,11,"BOGOTÁ, D.C.",11001,"BOGOTÁ, D.C.",0610,Extracción de petróleo crudo,NaN,...,216847696868000.0,125812992019000.0,91034704849000.0,144820641934000.0,33406291190000.0,NaN,NaN,NaN,NaN,SUPERFINANCIERA
1,2,900112515,REFINERIA DE CARTAGENA S.A.,13,BOLÍVAR,13001,CARTAGENA DE INDIAS,1921,Fabricación de productos de la refinación del ...,NaN,...,42844949768948.0,16480903602221.0,26364046166727.0,27910347095288.0,2188258717171.0,NaN,NaN,NaN,NaN,SUPERSERVICIOS
2,3,890100577,AEROVIAS DEL CONTINENTE AMERICANO S.A. AVIANCA,11,"BOGOTÁ, D.C.",11001,"BOGOTÁ, D.C.",5111,Transporte aéreo nacional de pasajeros,NaN,...,17886971237998.0,19333652424242.0,-1446681186244.0,22520677111772.0,-801213587941.0,NaN,NaN,NaN,NaN,SUPERTRANSPORTE
3,4,830095213,ORGANIZACIÓN TERPEL S.A.,11,"BOGOTÁ, D.C.",11001,"BOGOTÁ, D.C.",4661,"Comercio al por mayor de combustibles sólidos,...",NaN,...,7481575073000.0,4473299528000.0,3008275545000.0,23603192495000.0,333411532000.0,NaN,NaN,NaN,NaN,SUPERFINANCIERA
4,5,900156264,NUEVA EMPRESA PROMOTORA DE SALUD S.A.,11,"BOGOTÁ, D.C.",11001,"BOGOTÁ, D.C.",8430,Actividades de planes de seguridad social de a...,NaN,...,5913636590000.0,5428427760000.0,485208830000.0,14777134070000.0,10400284000.0,NaN,NaN,NaN,NaN,SUPERSALUD

In [6]:
df_ssc['ACTIVOS_2023'].dtype

dtype('O')

llamo la columna y le pido que me diga que tipo de dato es, este caso como lo denomine string, lo toma como tipo object

In [7]:
df_ssc['ACTIVOS_2023'] = df_ssc['ACTIVOS_2023'].astype('float64')
df_ssc.head()

,RANKING,NIT,RAZON_SOCIAL,CODIGO_DEPARTAMENTO,DEPARTAMENTO,CODIGO_MUNICIPIO,MUNICIPIO,CIIU,DESCRIPCION_CIIU,AÑOS_EMPRESA,...,ACTIVOS_2022,PASIVOS_2022,PATRIMONIO_2022,INGRESOS_OPERACIONALES_2022,UTILIDAD_2022,DIRECCION,TELEFONO,CELULAR,EMAIL,SUPERVISOR
0,1,899999068,ECOPETROL S.A,11,"BOGOTÁ, D.C.",11001,"BOGOTÁ, D.C.",0610,Extracción de petróleo crudo,NaN,...,216847696868000.0,125812992019000.0,91034704849000.0,144820641934000.0,33406291190000.0,NaN,NaN,NaN,NaN,SUPERFINANCIERA
1,2,900112515,REFINERIA DE CARTAGENA S.A.,13,BOLÍVAR,13001,CARTAGENA DE INDIAS,1921,Fabricación de productos de la refinación del ...,NaN,...,42844949768948.0,16480903602221.0,26364046166727.0,27910347095288.0,2188258717171.0,NaN,NaN,NaN,NaN,SUPERSERVICIOS
2,3,890100577,AEROVIAS DEL CONTINENTE AMERICANO S.A. AVIANCA,11,"BOGOTÁ, D.C.",11001,"BOGOTÁ, D.C.",5111,Transporte aéreo nacional de pasajeros,NaN,...,17886971237998.0,19333652424242.0,-1446681186244.0,22520677111772.0,-801213587941.0,NaN,NaN,NaN,NaN,SUPERTRANSPORTE
3,4,830095213,ORGANIZACIÓN TERPEL S.A.,11,"BOGOTÁ, D.C.",11001,"BOGOTÁ, D.C.",4661,"Comercio al por mayor de combustibles sólidos,...",NaN,...,7481575073000.0,4473299528000.0,3008275545000.0,23603192495000.0,333411532000.0,NaN,NaN,NaN,NaN,SUPERFINANCIERA
4,5,900156264,NUEVA EMPRESA PROMOTORA DE SALUD S.A.,11,"BOGOTÁ, D.C.",11001,"BOGOTÁ, D.C.",8430,Actividades de planes de seguridad social de a...,NaN,...,5913636590000.0,5428427760000.0,485208830000.0,14777134070000.0,10400284000.0,NaN,NaN,NaN,NaN,SUPERSALUD

In [8]:
df_ssc['ACTIVOS_2023'].dtype

dtype('float64')

In [9]:
df_ssc['ACTIVOS_2023'] = df_ssc['ACTIVOS_2023'].astype(str)
df_ssc.head()

,RANKING,NIT,RAZON_SOCIAL,CODIGO_DEPARTAMENTO,DEPARTAMENTO,CODIGO_MUNICIPIO,MUNICIPIO,CIIU,DESCRIPCION_CIIU,AÑOS_EMPRESA,...,ACTIVOS_2022,PASIVOS_2022,PATRIMONIO_2022,INGRESOS_OPERACIONALES_2022,UTILIDAD_2022,DIRECCION,TELEFONO,CELULAR,EMAIL,SUPERVISOR
0,1,899999068,ECOPETROL S.A,11,"BOGOTÁ, D.C.",11001,"BOGOTÁ, D.C.",0610,Extracción de petróleo crudo,NaN,...,216847696868000.0,125812992019000.0,91034704849000.0,144820641934000.0,33406291190000.0,NaN,NaN,NaN,NaN,SUPERFINANCIERA
1,2,900112515,REFINERIA DE CARTAGENA S.A.,13,BOLÍVAR,13001,CARTAGENA DE INDIAS,1921,Fabricación de productos de la refinación del ...,NaN,...,42844949768948.0,16480903602221.0,26364046166727.0,27910347095288.0,2188258717171.0,NaN,NaN,NaN,NaN,SUPERSERVICIOS
2,3,890100577,AEROVIAS DEL CONTINENTE AMERICANO S.A. AVIANCA,11,"BOGOTÁ, D.C.",11001,"BOGOTÁ, D.C.",5111,Transporte aéreo nacional de pasajeros,NaN,...,17886971237998.0,19333652424242.0,-1446681186244.0,22520677111772.0,-801213587941.0,NaN,NaN,NaN,NaN,SUPERTRANSPORTE
3,4,830095213,ORGANIZACIÓN TERPEL S.A.,11,"BOGOTÁ, D.C.",11001,"BOGOTÁ, D.C.",4661,"Comercio al por mayor de combustibles sólidos,...",NaN,...,7481575073000.0,4473299528000.0,3008275545000.0,23603192495000.0,333411532000.0,NaN,NaN,NaN,NaN,SUPERFINANCIERA
4,5,900156264,NUEVA EMPRESA PROMOTORA DE SALUD S.A.,11,"BOGOTÁ, D.C.",11001,"BOGOTÁ, D.C.",8430,Actividades de planes de seguridad social de a...,NaN,...,5913636590000.0,5428427760000.0,485208830000.0,14777134070000.0,10400284000.0,NaN,NaN,NaN,NaN,SUPERSALUD

In [13]:
df_ssc['ACTIVOS_2023'].dtype

dtype('O')

In [15]:
# Archivo txt
df_mun = pd.read_csv('Base_municipios.txt', sep="|", decimal=',', encoding ='utf-8', converters={'Cod. Municiopio':str})
df_mun.head()

,Cod. Municipio,Departamento,Municipio,Población municipio,Subregión PDET,ZOMAC,Valor agregado municipio,% Act. primarias municipio,% Act. secundarias municipio,% Act. terciarias municipio,...,% pobl. con pregrado municipio,% pobl. con posgrado municipio,% pobreza municipio,% informalidad municipio,% mujeres municipio,% jóvenes municipio,% pobl. con discapacidad municipio,% grupos étnicos municipio,% pobl. campesina municipio,% pobl. LGBT municipio
0,5001,Antioquia,Medellín,2572350,NaN,0,66432.277749,0.178603,20.059981,79.761415,...,11.826727,3.469121,12.8,71.0,52.910801,24.484810,6.272441,2.594917,1.903484,1.744767
1,5002,Antioquia,Abejorral,21109,NaN,1,314.197629,45.434607,6.372656,48.192737,...,1.727371,0.846639,40.6,87.5,47.790042,20.507840,16.046366,0.363657,NaN,NaN
2,5004,Antioquia,Abriaquí,2804,NaN,1,38.475494,37.042105,6.451563,56.506333,...,2.686429,1.065308,34.8,87.6,45.791726,22.039943,16.720704,2.037981,NaN,NaN
3,5021,Antioquia,Alejandría,4874,NaN,1,67.954333,18.023969,6.893189,75.082842,...,2.917426,0.729357,31.9,87.1,50.389824,20.106689,8.101068,0.312581,NaN,NaN
4,5030,Antioquia,Amagá,31851,NaN,0,635.925858,6.837485,46.197537,46.964978,...,2.952910,0.704672,22.9,69.5,50.915199,23.255157,9.022781,0.518251,NaN,NaN

In [16]:
df_mun2 = pd.read_csv('Base_municipios.txt', sep="|", decimal=',', encoding ='utf-8')
df_mun2.head()

,Cod. Municipio,Departamento,Municipio,Población municipio,Subregión PDET,ZOMAC,Valor agregado municipio,% Act. primarias municipio,% Act. secundarias municipio,% Act. terciarias municipio,...,% pobl. con pregrado municipio,% pobl. con posgrado municipio,% pobreza municipio,% informalidad municipio,% mujeres municipio,% jóvenes municipio,% pobl. con discapacidad municipio,% grupos étnicos municipio,% pobl. campesina municipio,% pobl. LGBT municipio
0,5001,Antioquia,Medellín,2572350,NaN,0,66432.277749,0.178603,20.059981,79.761415,...,11.826727,3.469121,12.8,71.0,52.910801,24.484810,6.272441,2.594917,1.903484,1.744767
1,5002,Antioquia,Abejorral,21109,NaN,1,314.197629,45.434607,6.372656,48.192737,...,1.727371,0.846639,40.6,87.5,47.790042,20.507840,16.046366,0.363657,NaN,NaN
2,5004,Antioquia,Abriaquí,2804,NaN,1,38.475494,37.042105,6.451563,56.506333,...,2.686429,1.065308,34.8,87.6,45.791726,22.039943,16.720704,2.037981,NaN,NaN
3,5021,Antioquia,Alejandría,4874,NaN,1,67.954333,18.023969,6.893189,75.082842,...,2.917426,0.729357,31.9,87.1,50.389824,20.106689,8.101068,0.312581,NaN,NaN
4,5030,Antioquia,Amagá,31851,NaN,0,635.925858,6.837485,46.197537,46.964978,...,2.952910,0.704672,22.9,69.5,50.915199,23.255157,9.022781,0.518251,NaN,NaN

In [17]:
# Archivo Excel
df_divipola_depto = pd.read_excel("2025-01-14 DIVIPOLA.xlsx",
                            sheet_name="Departamentos",
                            skiprows=9)
df_divipola_depto.head()

  Código        Nombre
0     05     ANTIOQUIA
1     08     ATLÁNTICO
2     11  BOGOTÁ, D.C.
3     13       BOLÍVAR
4     15        BOYACÁ

In [18]:
# Archivo Excel
df_divipola_mun = pd.read_excel("2025-01-14 DIVIPOLA.xlsx",
                            sheet_name="Municipios",
                            skiprows=10, dtype=str)
df_divipola_mun.head()

,Código,Nombre,Código .1,Nombre.1,Unnamed: 4,Unnamed: 5
0,05,ANTIOQUIA,05001,MEDELLÍN,Municipio,ÁREA METROPOLITANA DEL VALLE DE ABURRÁ
1,05,ANTIOQUIA,05002,ABEJORRAL,Municipio,NaN
2,05,ANTIOQUIA,05004,ABRIAQUÍ,Municipio,NaN
3,05,ANTIOQUIA,05021,ALEJANDRÍA,Municipio,NaN
4,05,ANTIOQUIA,05030,AMAGÁ,Municipio,NaN

In [19]:
# Renombrar las columnas
df_divipola_mun.rename(columns={'Código':'Cod. Depto',
                                'Nombre': 'Departamento',
                                'Código .1':'Cod. Municipio',
                                'Nombre.1': 'Municipio',
                                'Unnamed: 4': 'Tipo',
                                'Unnamed: 5': 'Area Metropolitana'},
                       inplace=True)
df_divipola_mun.head(6)

,Código,Departamento,Cod. Municipio,Municipio,Tipo,Area Metropolitana
0,05,ANTIOQUIA,05001,MEDELLÍN,Municipio,ÁREA METROPOLITANA DEL VALLE DE ABURRÁ
1,05,ANTIOQUIA,05002,ABEJORRAL,Municipio,NaN
2,05,ANTIOQUIA,05004,ABRIAQUÍ,Municipio,NaN
3,05,ANTIOQUIA,05021,ALEJANDRÍA,Municipio,NaN
4,05,ANTIOQUIA,05030,AMAGÁ,Municipio,NaN
5,05,ANTIOQUIA,05031,AMALFI,Municipio,NaN

### Importar el archivo desde Google Drive

In [20]:
import os

📌 Librería `os` en Python – Comandos más usados

La librería "os" conecta Python con el sistema operativo para manipular archivos, directorios y configuraciones.  

| Comando | Descripción | Ejemplo |
|---------|-------------|---------|
| `os.getcwd()` | Devuelve el directorio de trabajo actual. | `os.getcwd()` |
| `os.listdir(ruta)` | Lista los archivos y carpetas de una ruta. | `os.listdir(".")` |
| `os.chdir(ruta)` | Cambia el directorio de trabajo. | `os.chdir("C:/Users")` |
| `os.mkdir(nombre)` | Crea una nueva carpeta. | `os.mkdir("datos")` |
| `os.makedirs(ruta)` | Crea carpetas anidadas. | `os.makedirs("carpeta1/carpeta2")` |
| `os.remove(archivo)` | Elimina un archivo. | `os.remove("archivo.txt")` |
| `os.rmdir(carpeta)` | Elimina una carpeta vacía. | `os.rmdir("datos")` |
| `os.rename(src, dst)` | Renombra o mueve un archivo/carpeta. | `os.rename("a.txt","b.txt")` |
| `os.path.exists(ruta)` | Verifica si una ruta existe. | `os.path.exists("datos")` |
| `os.path.join(a, b)` | Une rutas de forma segura. | `os.path.join("carpeta", "archivo.csv")` |


⚠️ **Nota:**  
`os.remove` y `os.rmdir` no envían a la papelera, eliminan de forma permanente.

In [24]:
from google.colab import drive, files
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [27]:
# Para establecer el directorio de los archivos
os.chdir('/content/drive/MyDrive/Clase AI y Programación')

In [28]:
df_mun_drive = pd.read_csv('Base_municipios_drive.txt', sep="|", decimal=',', encoding ='utf-8', converters={'Cod. Municipio':str})
df_mun_drive.head()

,Cod. Municipio,Departamento,Municipio,Población municipio,Subregión PDET,ZOMAC,Valor agregado municipio,% Act. primarias municipio,% Act. secundarias municipio,% Act. terciarias municipio,...,% pobl. con pregrado municipio,% pobl. con posgrado municipio,% pobreza municipio,% informalidad municipio,% mujeres municipio,% jóvenes municipio,% pobl. con discapacidad municipio,% grupos étnicos municipio,% pobl. campesina municipio,% pobl. LGBT municipio
0,05001,Antioquia,Medellín,2572350,NaN,0,66432.277749,0.178603,20.059981,79.761415,...,11.826727,3.469121,12.8,71.0,52.910801,24.484810,6.272441,2.594917,1.903484,1.744767
1,05002,Antioquia,Abejorral,21109,NaN,1,314.197629,45.434607,6.372656,48.192737,...,1.727371,0.846639,40.6,87.5,47.790042,20.507840,16.046366,0.363657,NaN,NaN
2,05004,Antioquia,Abriaquí,2804,NaN,1,38.475494,37.042105,6.451563,56.506333,...,2.686429,1.065308,34.8,87.6,45.791726,22.039943,16.720704,2.037981,NaN,NaN
3,05021,Antioquia,Alejandría,4874,NaN,1,67.954333,18.023969,6.893189,75.082842,...,2.917426,0.729357,31.9,87.1,50.389824,20.106689,8.101068,0.312581,NaN,NaN
4,05030,Antioquia,Amagá,31851,NaN,0,635.925858,6.837485,46.197537,46.964978,...,2.952910,0.704672,22.9,69.5,50.915199,23.255157,9.022781,0.518251,NaN,NaN

## Importar datos desde una URL

In [29]:
# CSV desde URL
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df_url = pd.read_csv(url)
df_url.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

## Conectarse a una API

- API significa Application Programming Interface o Interfaz de Programación de Aplicaciones.

- Es un conjunto de reglas y herramientas que permite que dos aplicaciones se comuniquen entre sí.

- Una aplicación expone sus funcionalidades o datos a través de la API.

- Otra aplicación puede usarlos, sin necesidad de saber cómo funciona internamente.

- Una API es como un puente que permite a diferentes programas hablar entre sí y compartir información de manera segura y estandarizada.

### Conexión a datos del Banco Mundial (usando wbdata)

El Banco Mundial tiene una API que expone datos de desarrollo económico y social. En Python podemos usar la librería **wbdata**.

Documentación: https://wbdata.readthedocs.io/en/stable/

También se puede utilizar: **wbgapi**

Documentación: https://pypi.org/project/wbgapi/

In [31]:
!pip install wbdata

Requirement already satisfied: wbdata in /usr/local/lib/python3.13/dist-packages (1.1.0)
Requirement already satisfied: appdirs<2,>=1.4 in /usr/local/lib/python3.13/dist-packages (from wbdata) (1.4.4)
Requirement already satisfied: backoff<3,>=2.2.1 in /usr/local/lib/python3.13/dist-packages (from wbdata) (2.2.1)
Requirement already satisfied: cachetools<6,>=5.3.2 in /usr/local/lib/python3.13/dist-packages (from wbdata) (5.5.2)
Requirement already satisfied: dateparser<2,>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from wbdata) (1.4.2)
Requirement already satisfied: decorator<6,>=5.1.1 in /usr/local/lib/python3.13/dist-packages (from wbdata) (5.3.1)
Requirement already satisfied: requests<3,>=2.0 in /usr/local/lib/python3.13/dist-packages (from wbdata) (2.32.4)
Requirement already satisfied: shelved-cache<0.4,>=0.3.1 in /usr/local/lib/python3.13/dist-packages (from wbdata) (0.3.1)
Requirement already satisfied: tabulate<1,>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from wbdata) (0.9.0)
Requirement already satisfied: python-dateutil>=2.7.0 in /usr/local/lib/python3.13/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2.9.0.post0)
Requirement already satisfied: pytz>=2024.2 in /usr/local/lib/python3.13/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2025.2)
Requirement already satisfied: regex>=2024.9.11 in /usr/local/lib/python3.13/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2025.11.3)
Requirement already satisfied: tzlocal>=0.2 in /usr/local/lib/python3.13/dist-packages (from dateparser<2,>=1.2.0->wbdata) (5.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.0->wbdata) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.0->wbdata) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.0->wbdata) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.0->wbdata) (2026.7.22)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7.0->dateparser<2,>=1.2.0->wbdata) (1.17.0)

In [34]:
import wbdata
import datetime

Nota: "datetime" permite trabajar con fechas y horas.

- Obtener la fecha y hora actual.
- Crear objetos de fecha (año, mes, día).
- Realizar operaciones con fechas (sumar o restar días, calcular diferencias).
- Dar formato a fechas (por ejemplo, mostrar como "31-08-2025" en lugar de "2025-08-31").

El constructor datetime.datetime() acepta argumentos de fecha y hora en el siguiente orden:

datetime.datetime(year, month, day, hour=0, minute=0, second=0, microsecond=0)

hour: Hora (0-23)

minute: Minuto (0-59)

second: Segundo (0-59)

microsecond: Microsegundo (0-999999)

Si no se especifica la hora, minuto o segundo, Python los establecerá en 0 por defecto.

Vamos a traer el PIB per cápita de Colombia entre 2010 y 2023 directamente desde el Banco Mundial.

In [35]:
# Indicador: PIB per cápita (en USD actuales)
# País: Colombia (COL)
indicador = {"NY.GDP.PCAP.CD": "PIB per cápita"}

# El orden es: año (2010), mes (1), día (1)
fecha_inicio = datetime.datetime(2010, 1, 1)
# El orden es: año (2023), mes (1), día (1)
fecha_fin = datetime.datetime(2023, 1, 1)

# Descargar datos
df = wbdata.get_dataframe(indicador, country="COL", date=(fecha_inicio, fecha_fin))

df

      PIB per cápita
date
2023     7012.491691
2022     6680.445069
2021     6222.621644
2020     5339.687114
2019     6472.545449
2018     6816.968183
2017     6479.532313
2016     5959.842504
2015     6248.514905
2014     8187.208249
2013     8279.102556
2012     8108.598382
2011     7400.994070
2010     6398.295845

### Conexión a datos abiertos de Colombia

https://www.datos.gov.co/

#### Ejemplos

1. MEN_ESTADISTICAS_EN_EDUCACION_EN_PREESCOLAR, BÁSICA Y MEDIA_POR_DEPARTAMENTO

https://www.datos.gov.co/Educaci-n/MEN_ESTADISTICAS_EN_EDUCACION_EN_PREESCOLAR-B-SICA/ji8i-4anb/about_data

Ir a Exportar --> API de acceso y copiar el endpoint solamente.

In [ ]:
import requests

"requests" es una librería que permite hacer peticiones HTTP (GET, POST, PUT, DELETE) de manera sencilla.

GET → traer datos desde una página o API.

POST → enviar datos a un servidor.

In [ ]:
url = "https://www.datos.gov.co/resource/ji8i-4anb.json"

# Solicitud a la API
response = requests.get(url)
data = response.json()

# Convertir a DataFrame
df = pd.dataframe(data)

df.head()

2. Casos positivos de COVID-19 en Colombia

In [ ]:
url = "https://www.datos.gov.co/resource/gt2j-8ykr.json"

# Solicitud a la API
response = requests.get(url)
data = response.json()

# Convertir a DataFrame
df = pd.DataFrame(data)

df.head()

## Explorar el dataset

In [ ]:
df

In [ ]:
df.head()

In [ ]:
df.head(10)

In [ ]:
df.sample()

In [ ]:
# Para ver todas las filas, pero seleccionar ciertas columnas
# Opción 1
df.loc[:,['departamento_nom','edad','fecha_inicio_sintomas']]

In [ ]:
df.loc

In [ ]:
# Opción 2: solo seleccionar las columnas que quiero ver
df[['departamento_nom','edad','fecha_inicio_sintomas']]

In [ ]:
# Puedo crear un nuevo dataframe con las columnas que necesito solamente
df2 = df[['departamento_nom','edad','fecha_inicio_sintomas']].copy()
df2

In [ ]:
# Ver el nombre de todas las columnas

In [ ]:
df2.columns

In [ ]:
# Ver los tipos de datos de cada columna

In [ ]:
# Ver la cantidad de filas del df
len(df2)

In [ ]:
# Ver la cantidad de filas y columnas del df

In [ ]:
# Ver la cantidad de filas y columnas, el nombre todas las columnas, el tipo de datos y si tiene nulos